# Generated by Django 4.1.1 on 2022-09-19 16:53

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('company_description', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('time_employed', models.CharField(choices=[('0_1_year', '0-1 Year'), ('1_3_years', '1-3 Years'), ('3_5_years', '3-5 Years'), ('5_10_years', '5-10 Year'), ('10_year_plus', '10+ Years')], default='0_1_year', max_length=100)),
                ('still_employed', models.CharField(choices=[('prefer_to_not_say', 'Prefer To Not Say'), ('blank_blank', '......'), ('still_employed', 'Still Employed Here'), ('no_longer_employed', 'No Longer Employed Here')], default='no_longer_employed', max_length=100)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('issues_faced', models.TextField(default='', max_length=5000)),
                ('awkwardness_rating', models.CharField(blank=True, choices=[('1_5', '1/5'), ('2_5', '2/5'), ('3_5', '3/5'), ('4_5', '4/5'), ('5_5', '5/5')], default='', max_length=10, null=True)),
                ('sexual_orientation', models.CharField(blank=True, choices=[('prefer_to_not_say', 'Prefer To Not Say'), ('blank_blank', '......'), ('Allosexual', 'Allosexual'), ('Androsexual', 'Androsexual'), ('Asexual', 'Asexual'), ('Autosexual', 'Autosexual'), ('Bi-curious', 'Bi-curious'), ('Bisexual', 'Bisexual'), ('Closeted', 'Closeted'), ('Demisexual', 'Demisexual'), ('Fluid', 'Fluid'), ('Gay', 'Gay'), ('Graysexual', ' Graysexual'), ('Gynesexual', ' Gynesexual'), ('Heterosexual/straight', ' Heterosexual/straight'), ('Homosexual', ' Homosexual'), ('Lesbian', 'Lesbian'), ('Pansexual', 'Pansexual'), ('Queer', 'Queer'), ('Questioning', 'Questioning'), ('Sapiosexual', 'Sapiosexual'), ('Sex-repulsed', 'Sex-repulsed'), ('Skoliosexual', 'Skoliosexual'), ('Spectrasexual', 'Spectrasexual')], default='prefer_to_not_say', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('prefer_to_not_say', 'Prefer To Not Say'), ('blank_blank', '......'), ('Male', 'Male'), ('Female', 'Female'), ('Agender', 'Agender'), ('Androgyne', 'Androgyne'), ('Bigender', 'Bigender'), ('Butch', 'Butch'), ('Cisgender', 'Cisgender'), ('Gender Expansive', 'Gender Expansive'), ('Genderfluid', 'Genderfluid'), ('Gender Outlaw', 'Gender Outlaw'), ('Genderqueer', 'Genderqueer'), ('Masculine of Center', 'Masculine of Center'), ('Nonbinary', 'Nonbinary'), ('Omnigender', 'Omnigender'), ('Polygender/Pangender', 'Polygender/Pangender'), ('Transgender', 'Transgender'), ('Trans', 'Trans'), ('Two Spirit', 'Two Spirit')], default='prefer_to_not_say', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Main Form',
            },
        ),
    ]
